service: to-do-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-southeast-1

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:752853690663:table/tasks"

functions:
  # Defines an HTTP API endpoint that calls the main function in create-task.js
  # - path: url path is /tasks
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: create-task.main
    events:
      - http:
          path: tasks
          method: post
          cors: true
          authorizer: aws_iam
  get:
    # Defines an HTTP API endpoint that calls the main function in get-task.js
    # - path: url path is /tasks/{id}
    # - method: GET request
    handler: get-task.main
    events:
      - http:
          path: tasks/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    # Defines an HTTP API endpoint that calls the main function in list-tasks.js
    # - path: url path is /notes
    # - method: GET request
    handler: list-tasks.main
    events:
      - http:
          path: tasks
          method: get
          cors: true
          authorizer: aws_iam
  update:
    # Defines an HTTP API endpoint that calls the main function in update-task.js
    # - path: url path is /tasks/{id}
    # - method: PUT request
    handler: update-task.main
    events:
      - http:
          path: tasks/{id}
          method: put
          cors: true
          authorizer: aws_iam

